networks:
  app_network:
  db_network:

services:
  mysql-container:
    image: custom-mysql:v1
    container_name: mysql-container
    restart: always
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5


  spring-boot-container:
    build: . # docker img build pass code
    container_name: spring-boot-container
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - app_network
      - db_network


  nginx-container:
    image: img_nginx:v1
    container_name: nginx-container
    restart: always
    depends_on:
      - spring-boot-container
    ports:
      - "80:80"
    networks:
      - app_network
    stop_grace_period: 1s  # off command after 1s Shutdown