networks:
  app_network:
  db_network:

services:
  mysql-container:
    image: mysql:8.0.40
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_USER: newuser
      MYSQL_PASSWORD: qwer1234
    networks:
      - db_network
    volumes:
      - ./vol_mysql:/var/lib/mysql  # volume bind mount
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # db init
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3

  spring-boot-container:
    build: . # docker img build pass code
    container_name: spring-boot-container
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - app_network
      - db_network

  nginx-container:
    image: img_nginx:v1
    container_name: nginx-container
    restart: always
    depends_on:
      - spring-boot-container
    ports:
      - "80:80"
    networks:
      - app_network
    stop_grace_period: 1s  # off command after 1s Shutdown